version: "3.8"

services:
  app:
    build: .
    volumes:
      - .:/app
      - ./output:/app/output
    environment:
      - PYTHONUNBUFFERED=1
      - DISPLAY=192.168.3.7:0.0
    command: python main.py