version: "3.8"

services:
  app:
    build: .
    volumes:
      - .:/app
      - ./output:/app/output
    env_file:
      - ./.env
    environment:
      - PYTHONUNBUFFERED=1
      - DISPLAY=host.docker.internal:0
    command: python scheduler.py
